#pos = 3, 14
experiment:
  name: "ship_localization_qaa_ibmq_16x16"
  output_dir: "outputs/ship_localization_qaa_ibmq_16x16"
  output:
    save_cpd_md: true
    save_circuit_image: true

network:
  builder: "generator"
  save_image: true
  type: "ship_localization"
  params:
    grid_size: 16
    lighthouses:
      - [1, 5]
      - [3, 12]
    num_dist_bins: 16
    num_bear_bins: 16
    dist_noise: [0.95, 0.03, 0.01, 0.01]
    bear_noise: [0.95, 0.03, 0.01, 0.01]

inference:
  compiler: "QAA"
  encoding: "binary"
  encoding_params: {}
  baseline:
    enabled: true
    method: "variable_elimination"
    params: {}
  circuit:
    shots: 4096
    seed: 123
  backend:
    type: "qiskit_ibm"
    device: "ibm_fez"
    wires: 4
  evidence:
    Dist1: 8
    Bear1: 11
    Dist2: 1
    Bear2: 12
  query:
    - "X"
    - "Y"
