experiment:
  name: "ship_localization_qaa_ibmq_32x32"
  output_dir: "outputs/ship_localization_qaa_ibmq_32x32"
  output:
    save_cpd_md: true
    save_circuit_image: true

network:
  builder: "generator"
  save_image: true
  type: "ship_localization"
  params:
    grid_size: 32
    lighthouses:
      - [30, 5]
      - [17, 25]
    num_dist_bins: 32
    num_bear_bins: 32
    dist_noise: [0.95, 0.03, 0.01, 0.01]
    bear_noise: [0.95, 0.03, 0.01, 0.01]

inference:
  compiler: "QAA"
  encoding: "one_hot"
  baseline:
    enabled: true
    method: "variable_elimination"
    params: {}
  circuit:
    shots: 4096
    seed: 123
  backend:
    type: "qiskit_ibm"
    device: "ibm_fez"
    wires: 4
  evidence:
    Dist1: 20
    Bear1: 27
    Dist2: 2
    Bear2: 0
  query:
    - "X"
    - "Y"
