# pos = 36, 25
experiment:
  name: "ship_localization_qaa_ibmq_64x64_one_hot"
  output_dir: "outputs/ship_localization_qaa_ibmq_64x64_one_hot"
  output:
    save_cpd_md: true
    save_circuit_image: true

network:
  builder: "generator"
  save_image: true
  type: "ship_localization"
  params:
    grid_size: 64
    lighthouses:
      - [40, 39]
      - [12, 52]
    num_dist_bins: 64
    num_bear_bins: 64
    dist_noise: [0.95, 0.03, 0.01, 0.01]
    bear_noise: [0.95, 0.03, 0.01, 0.01]

inference:
  compiler: "QAA"
  encoding: "one_hot"
  encoding_params:
    k: 16
    marginalize: []
  baseline:
    enabled: true
    method: "variable_elimination"
    params: {}
  circuit:
    shots: 4096
    seed: 123
  backend:
    type: "qiskit_ibm"
    device: "ibm_fez"
    wires: 128
  evidence:
    Dist1: 16
    Bear1: 13
    Dist2: 31
    Bear2: 23
  query:
    - "X"
    - "Y"
