experiment:
  name: "ship_localization_qaa"
  output_dir: "outputs/ship_localization_qaa"
  output:
    save_cpd_md: true
    save_circuit_image: true

network:
  builder: "generator"
  save_image: true
  type: "ship_localization"
  params:
    grid_size: 8
    lighthouses:
      - [1, 1]
    num_dist_bins: 8
    num_bear_bins: 8
    dist_noise: [0.95, 0.03, 0.01, 0.01]
    bear_noise: [0.95, 0.03, 0.01, 0.01]
    #dist_noise: [0.0, 0.0, 0.0, 0.0]
    #bear_noise: [0.0, 0.0, 0.0, 0.0]

inference:
  compiler: "DCM"
  encoding: "binary"
  encoding_params: {}
  baseline:
    enabled: true
    method: "variable_elimination"
    params: {}
  circuit:
    shots: 1024
    seed: 123
  backend:
    type: "pennylane.simulator"
    device: "default.qubit"
    wires: null
  evidence:
    Dist1: 2
    Bear1: 5
  query:
    - "X"
    - "Y"
